name: Publish

on:
  push:
    tags:
      - v*
  workflow_dispatch:

defaults:
  run:
    shell: 'bash -Eeuo pipefail -x {0}'

env:
  IMAGE_STAGING: quay.io/enterprisedb/pgbouncer-testing
  IMAGE_RELEASE: quay.io/enterprisedb/pgbouncer

jobs:
  build-and-publish:
    runs-on: ubuntu-20.04
    steps:
      -
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
      -
        name: Detect platforms
        id: docker-platforms
        run: |
          # Available architecture on UBI8 are: linux/amd64, linux/arm64, linux/ppc64le, linux/s390x
          # Keep in mind that adding more platforms (architectures) will increase the building
          # time even if we use the ghcache for the building process.
          platforms="linux/amd64,linux/arm64,linux/ppc64le,linux/s390x"
          echo "::set-output name=platforms::${platforms}"
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: ${{ steps.docker-platforms.outputs.platforms }}
      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to quay.io
        uses: docker/login-action@v1.10.0
        with:
          registry: quay.io/enterprisedb
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_TOKEN }}
      -
        name: Tag Docker image
        id: docker-meta
        run: |
          if git describe --tags; then
            image_tag=$(git describe --tags)
            image_tag=${image_tag##v}
          else
            # Set a default if we have no tags yet
            image_tag=0.0.1-1-$(git rev-parse --short HEAD)
          fi
          # If we are running the pipeline on a tag images are pushed in both
          # testing and prod, only testing otherwise
          if [[ "${GITHUB_REF}" =~ refs/tags/v(.*) ]]; then
            result="${IMAGE_RELEASE}:${image_tag},${IMAGE_STAGING}:${image_tag}"
          else
            result="${IMAGE_STAGING}:${image_tag}"
          fi
          echo "::set-output name=tags::${result%,}"
      - 
        name: Build and push
        uses: docker/build-push-action@v2.7.0
        with:
          platforms: ${{ steps.docker-platforms.outputs.platforms }}
          context: .
          push: true
          tags: ${{ steps.docker-meta.outputs.tags }}
